Compare baselines xpvwrh
mrc-ide/gonovax pull request #105
Opened 2022-04-25 11:36 UTC by Dariyanikitin

tweaked extract flows and compare_baselines to work for the new analyis

2022-04-28 15:11 UTC, lwhittles requested changes

2022-04-28 15:11 UTC, lwhittles commented on R/run_grid.R
> +                                            ret$inc_primary_part_doses
```suggestion
  ret$inc_primary_full_doses <- ret$inc_primary *  uptake_second_dose * 2
  ret$inc_primary_part_doses <- ret$inc_primary * (1 - uptake_second_dose)
  ret$inc_primary_total_doses <- ret$inc_primary_full_doses + ret$inc_primary_part_doses
```
first dose uptake should already be applied here, i.e. the number of peope moving from X to either P or V is number offered * first dose uptake. Then it's second dose uptake that determines whether they get 1 dose or 2.

Also, I don't think you multiplied the full doses by 2

2022-04-28 15:11 UTC, lwhittles commented on R/support.R
> +                            - cumulative_flows$cum_part_to_full
Have you checked anywhere that this is the case? i.e. that cum_revaccinated = t(aggregate(y, "cum_vaccinated", stratum = 4))?

2022-04-28 15:11 UTC, lwhittles commented on tests/testthat/test-run_grid.R
> +  }
I think this check is incorrect as well (for reasons outlined above) To make sure this doesn't happen again, can you put in a check where second dose uptake = 100%, no revaccination and no P -> V, then the total doses should be 2 x number of vaccinations.

Similarly, can you add a check where 2nd dose uptake = 0%, no VBE, then total doses should = total vaccinations.

2022-04-28 16:08 UTC, Dariyanikitin commented on R/support.R
> +                            - cumulative_flows$cum_part_to_full
I hadn't but i think its simpler just to change what i've done to   what you're suggesting as its less convoluted :)

2022-04-29 11:39 UTC, lwhittles approved these changes
looks good to me!

2022-04-29 11:49 UTC, merged