Vaccine protected
mrc-ide/gonovax pull request #107
Opened 2022-08-11 16:53 UTC by Dariyanikitin

model now outputs the number of individuals under different types of vaccine protection and downstream calculates proportion of the population under vaccine protection

2022-08-12 06:48 UTC, lwhittles requested changes

2022-08-12 06:48 UTC, lwhittles commented on R/run_grid.R
> +##' form of vaccine protection in a given year
these are prevalence measures, not incidence, so remove the `inc_` prefix and any reference to annual. I.e. this is just a snapshot of the number of vaccine protectedd individuals at the given moment

2022-08-12 06:48 UTC, lwhittles commented on R/run_grid.R
> +  N <- 6e+5
please don't hardcode this, extract it from the object in some way e.g. `N <- aggregate(y, "N")`

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +
again these are prevalence measures so cumulative versions don't make sense, I would move this entire section into `compare_baseline_xpvwrh` as otherwise you're doing strang things by treating preevalence as cumulative inicidence, then taking the differrence between years twice.

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +    t(aggregate(y, "N", stratum = c(3, 5), as_incid = TRUE))
```suggestion
    t(aggregate(y, "N", stratum = c(3, 5)))
```

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +    t(aggregate(y, "N", stratum = 2, as_incid = TRUE))
```suggestion
    t(aggregate(y, "N", stratum = 2))
```

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +    t(aggregate(y, "N", stratum = c(2, 3, 5), as_incid = TRUE))
```suggestion
    t(aggregate(y, "N", stratum = c(2, 3, 5)))
```

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +  cumulative_flows$cum_vacprotec_total <-
```suggestion
  cumulative_flows$vacprotec_total <-
```

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +  cumulative_flows$cum_vacprotec_part <-
```suggestion
  cumulative_flows$vacprotec_part <-
```

2022-08-12 06:48 UTC, lwhittles commented on R/support.R
> +  cumulative_flows$cum_vacprotec_full <-
```suggestion
  cumulative_flows$vacprotec_full <-
```

2022-08-12 06:48 UTC, lwhittles commented on tests/testthat/test-run_grid.R
> +  expect_true(all(z$inc_vacprotec_total_prop != 0))
I would improve these checks as they should have picked up that the code above is returning very small values - for example, if you initialise with a known proportion of people vaccinated / partially vaccinated, does the model extract that correct proportion?

2022-08-18 10:22 UTC, lwhittles requested changes

2022-08-18 10:22 UTC, lwhittles commented on R/run_grid.R
> +    # remove the 0
```suggestion
    # remove t = 0, so object dimensions for prevalence measures match those for annual and cumulative flows
```

2022-08-18 10:22 UTC, lwhittles commented on R/run_grid.R
> +    N <- t(aggregate(y, "N"))[1, 1]
```suggestion
    N <- aggregate(y, "N")[, -1]
```
This should work fine with the object dimensions as N will be a vector of length t, and `ret$vacprotec_full` etc will have dim `c(t, n_par)` (I think) and it means the code will still work if we ever moved to having a changing population size

2022-08-18 12:14 UTC, Dariyanikitin commented on R/run_grid.R
> +    # vaccine protected total, snapshot of N in: P(2), V(3), W(4)
this will go down in history as one of the stupidest mistakes I have made , the protected but waned people ?! :')

2022-08-18 13:38 UTC, lwhittles approved these changes

2022-08-18 14:24 UTC, merged