Adding erlang strata for xvw and xpvwrh
mrc-ide/gonovax pull request #110
Opened 2023-02-14 11:33 UTC by Dariyanikitin

* note, people can only be vaccinated  from P1 --> V1 but not P2 or P3 etc. If we ever need to add in full vaccination from partial vaccination we can tweak this then

2023-02-14 16:21 UTC, lwhittles requested changes

2023-02-14 16:21 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +  r <- i_v[(2 * n_erlang + 1):(3 * n_erlang)] #2 * n_erlang + 1 to 3 * n_erlang
again this would read easier if you used a universal index function

2023-02-14 16:21 UTC, lwhittles commented on R/onevax_xvw_trial.R
> +  cov <- c(1 - p_v, p_v, vector("numeric", n_erlang - 1), 0)
```suggestion
  cov <- c(1 - p_v, p_v, rep(0, n_erlang - 1), 0)
```

2023-02-14 16:21 UTC, lwhittles commented on R/onevax_xvw_trial.R
> +  ve <- append(c(0), append(rep(1, length(i_v)), 0))
```suggestion
  ve <- c(0, rep(1, n_erlang), 0)
```

2023-02-14 16:21 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +  n_vax <- 6 + (n_erlang - 1) * 3
In a comment below I discuss writing an index function that will make all this a lot clearer and make working out elligibility easier too

2023-02-14 16:23 UTC, lwhittles commented
Well done for getting it this far, before we merge can we have a pass at making the code more readable (and checkable)?
In particular, I've recommended
- writing a function that returns the stratum index to make it easier to reference, rather than recalculating each time which is ripe for errors
- always having erlang waning from left to right (too hard to keep track of otherwise)

2023-02-17 14:59 UTC, Dariyanikitin commented on R/onevax_xpvwrh.R
> +  i_p <- c(n_erlang + 1, n_erlang + 2, 2 + (3 * n_erlang))
Yes it is! i've changed it to this so it's easier to track and also added some commentary 
i_p <- c(idx$P[1], rep(idx$V[1], n_erlang + 1), idx$R[1])

2023-02-17 20:31 UTC, Dariyanikitin commented on R/onevax_xpvwrh.R
> +       w       = create_waning_map_branching(n_vax,
there is a line within the create_waning_map_branching function where the vector of rates becomes a vector of length 3* n_erlang to avoid this from happening, e.g if dur_p = 1e03, dur_v = 2e03, dur_revax = 3e03 then the z_erlang vector becomes:  0.0020000000 0.0020000000 0.0010000000 0.0010000000 0.0006666667 0.0006666667

2023-02-17 20:32 UTC, Dariyanikitin commented on R/onevax_xpvwrh.R
> +       w       = create_waning_map_branching(n_vax,
![image](https://user-images.githubusercontent.com/61972511/219787313-f6a9bcee-c8bb-491a-9758-f62439c73f14.png)

2023-02-17 20:32 UTC, Dariyanikitin commented on R/onevax_xpvwrh.R
> +       w       = create_waning_map_branching(n_vax,
I think this is right?

2023-02-20 15:11 UTC, lwhittles approved these changes

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +       w       = create_waning_map_branching(n_vax,
yep that looks good to me

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xpvwrh.R
>    vax_map[, 1, 1] <-  v
```suggestion
  vax_map[, idx$X, idx$X] <-  v
```

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +  vax_map[, idx$V[1], 1] <- -v
```suggestion
  vax_map[, idx$V[1], idx$X] <- -v
```

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +  ve_vec <- c(rep(0, idx$n_vax))
```suggestion
  ve_vec <- rep(0, idx$n_vax)
```

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xpvwrh.R
> +    ret$V <- max(ret$P) +  seq_len(n_erlang)
```suggestion
    ret$V <- max(ret$P) + seq_len(n_erlang)
```

2023-02-20 15:11 UTC, lwhittles commented on R/onevax_xvw_trial.R
> +   i_w <- idx$V + 1
clever!

2023-02-20 18:42 UTC, merged