Including diagnosis history in population level model
mrc-ide/gonovax pull request #120
Opened 2024-02-15 14:44 UTC by tsleng93

Added in diagnosis history to main gonovax model.

The model now substratifies each stratum by the number of times an individual has been diagnosed an individual has been diagnosed in the previous Y years.

The number of diagnosis history strata is specified by n_diag_rec. For d < n_diag_rec an individual in diagnosis history strata $d$ has been diagnosed $d-1$ times in the last year.  If d = n_diag_rec, an individual in diagnosis history strata $d$ has been diagnosed $d-1$ or more times in the last year.

The model with diagnosis history has been tested extensively for compatibility with xpvwrh, which is also compatible with having number of erlang states

All other vaccination strategies have been tested extensively with n_diag_rec = 1. These *should* also work fine for n_diag_rec > 1, but more extensive testing is required.

2024-02-19 13:40 UTC, lwhittles requested changes

2024-02-19 13:40 UTC, lwhittles commented on R/onevax_xvw.R
> +  i_v_temp <- c((1 * (n_diag_rec) + 1): (2 * (n_diag_rec)))
```suggestion
  i_v_temp <- i_v[1:n_diag_rec]
```
Is this clearer what's going on?

2024-02-19 13:40 UTC, lwhittles commented on R/onevax_xvw.R
> +      i_v_temp2 <- i_v_temp[-c(1, (n_diag_rec + 1))]
I'm confused by these two linees as by my reckoning i_eligible_temp and i_v_temp should only have n_diag_rec elements...

2024-02-19 13:40 UTC, lwhittles commented on R/onevax_xvw.R
> +
```suggestion
    if (!is.null(strategy) && (strategy == "VaH" || strategy == "VaHonly")) {
      i_eligible_vos <- i_eligible[-1] # only eligible after first diagnosis
      i_v_vos <- i_v[-1]
    } else {
      i_eligible_vos <- i_eligible
      i_v_vos <- i_v
    }
```

2024-02-19 13:40 UTC, lwhittles commented on R/onevax_xvw.R
> +
would this work? (with onward updates of course. It all looks correct, but I wonder if it would be easier to read if all the calculation of indices  (e.g. i_eligible etc) happended within `stratum_index_XXX` functions that could take a 'strategy' argument themselves, then outputs `idx$eligible, idx$eligble_vos, idx$new_vaccinees, idx$new_vaccinees_vos` etc which might make the code easier to follow?

2024-02-19 14:22 UTC, tsleng93 commented on R/onevax_xvw.R
> +      i_v_temp2 <- i_v_temp[-c(1, (n_diag_rec + 1))]
yep you're right, this is a mistake (this was copy and pasted over from xvwv)

2024-02-19 14:23 UTC, tsleng93 commented on R/onevax_xvw.R
> +
That seems like a good idea. I'll work on that

2024-02-22 16:26 UTC, richfitz commented
Right - I've got a fix up for odin that fixes the format errors here (https://github.com/mrc-ide/odin/pull/312). I tried getting this working in a PR (https://github.com/mrc-ide/gonovax/pull/121) but of course that does not work because you need to regenerate the odin sources for your project.  I tried that locally and it changed rather a lot - more than I would have expected and of this looks like it would be changing to your model itself. Previously you built with 1.4.7 and I get a big changeset there too, but I can't see if that is just a sorting change.

Certainly looking at the files in inst/odin makes me think that the current version of the files here might not be quite the most recent they could be, but I've also forgotten how odin does this.  But the names of the generated code and inputs don't align very well which is consistent with things needing regenerating.

I suggest you make sure you're happy with the odin code, then upgrade to odin and regenerate.  Using the version in the PR will get you the fix, we'll have that merged soon though.

2024-02-23 12:18 UTC, richfitz commented
The odin fix is now on master, so you can use that now

2024-02-23 14:16 UTC, lwhittles approved these changes

2024-02-23 14:16 UTC, merged