Partner notification and vaccination on notification
mrc-ide/gonovax pull request #129
Opened 2024-05-03 13:08 UTC by tsleng93

Added in simple implementation of partner notification into model

The model now has two new input parameters:
- kappa, the ratio between diagnoses and partner notifications
- notifiedprev, the prevalence among notified partners

Added in vaccination by notification, which works with all vax_strat  options

other changes
- the number of years that individuals are recorded as having a history of gonorrhoea is no longer hardcoded, and is included as a parameter, years_history in functions

2024-05-29 12:26 UTC, lwhittles requested changes

2024-05-29 12:26 UTC, lwhittles commented on inst/odin/model.R
> +  (1 - epsilon) * Up[j] / sum(Up[])
```suggestion
omega_C[, ] <- (1 - epsilon) * Cp[j] / sum(Cp[]) + (if (i == j) epsilon else 0)
omega_U[, ] <- (1 - epsilon) * Up[j] / sum(Up[]) + (if (i == j) epsilon else 0)
```

2024-06-07 09:00 UTC, tsleng93 commented on R/onevax_xvwr.R
> +    w       = create_waning_map(n_vax, i_v, i_w, 1 / c(dur, dur_revax),
Yes, it was introduced at the merge 'including diagnosis history at the population level'. I've now changed the stopifnot condition in create_waning_map, which will mean tests will fail if a similar error is introduced.

2024-06-07 09:32 UTC, tsleng93 commented
> Looks good and matches the equations you sent me - could you fix the confilcts as well please and I'll re-review and get it merged :)

I'm not quite sure how to go about fixing the conflicts to do with automatically generated files (R/odin.R, inst/odin/model.json, src/odin.c).  What do you recommend?

2024-07-02 14:53 UTC, lwhittles approved these changes

2024-07-02 14:53 UTC, merged