Additional outputs
mrc-ide/gonovax pull request #132
Opened 2024-12-12 11:15 UTC by Dariyanikitin

added in additional outputs in comparebaseline xpvwrh needed for final analysis - percentage cases averted annual and cumulative etc

2024-12-12 19:36 UTC, lwhittles requested changes

2024-12-12 19:36 UTC, lwhittles commented on R/run_grid.R
> +  ret$cum_percentage_diag_avert <- (abs(diff_diag_cum) / total_diag_cum * 100)
Should these have `abs`? I think the sign is important here, if you want them to be cases averted just use `-`

2024-12-13 09:09 UTC, Dariyanikitin commented on R/run_grid.R
> +  ret$cum_percentage_diag_avert <- (abs(diff_diag_cum) / total_diag_cum * 100)
I see your point! So if the vaccine was harmful and increased cases compared to the baseline i.e 'diff' is +'ve we'd want that reflected in the percentage cases averted which should be negative ! Will amend asap

2024-12-13 12:17 UTC, lwhittles approved these changes

2024-12-13 12:17 UTC, merged